"""ORM model definitions for application data.

Currently includes a single `Summary` model used to persist generated
summaries for different source types (PDF uploads or YouTube videos).

Design notes:
- `id`: stored as a string; you can migrate to UUID type for stronger guarantees.
- `user_id`: plain string for now. Replace with ForeignKey('users.id') once a users table exists.
- `source_type`: distinguishes origin (e.g. 'pdf', 'youtube'); consider Enum for data integrity.
- `source_url`: optional; present for YouTube or remote PDF link, null for direct file uploads.
- `created_at`: auto-populated timestamp (UTC) on insertion.
"""

from sqlalchemy import Column, String, Text, DateTime, ForeignKey
from sqlalchemy.orm import declarative_base
from datetime import datetime

# Declarative base that holds metadata for all models.
Base = declarative_base()

class Summary(Base):
    """Persisted summary of processed source content."""
    __tablename__ = "summaries"

    # Primary key (string). Recommend using UUIDs generated by application code.
    id = Column(String, primary_key=True)
    # User owning the summary (string placeholder; make FK later).
    user_id = Column(String, index=True)
    # Origin type: 'pdf' or 'youtube'; could be extended to others.
    source_type = Column(String)
    # Original source URL (YouTube link or remote file). Nullable for direct uploads.
    source_url = Column(Text, nullable=True)
    # Title extracted from source or provided by user.
    title = Column(String)
    # Generated summary text body.
    summary_text = Column(Text)
    # Creation timestamp (UTC) when record is inserted.
    created_at = Column(DateTime, default=datetime.utcnow)
