"""
Main application entry point for the Smart Content Finder API.

Responsibilities:
- Create and configure the FastAPI application instance
- Register feature routers (PDF, YouTube, Auth) with URL prefixes and tags
- Expose a simple root/health endpoint for quick availability checks
"""

# FastAPI framework core application class
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

# Import APIRouter instances from route modules.
# We alias each module-level `router` to a descriptive name for clarity.
from app.routes.pdf_routes import router as pdf_router
from app.routes.yt_routes import router as yt_router
from backend.app.routes.auth.auth_routes import router as auth_router
# from backend.app.routes.summary import router as summary_router
from app.routes import summary


# Instantiate the FastAPI app.
# The `title` is shown in the autogenerated OpenAPI docs (at /docs or /redoc).
app = FastAPI(title="Smart Content Finder API")

# CORS configuration: allow the Next.js frontend (localhost:3000) to call the API from the browser.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:3000", "http://127.0.0.1:3000"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# Register feature routers with URL prefixes and OpenAPI tags.
# - prefix: URL path segment added before all routes in that router
app.include_router(pdf_router, prefix="/pdf", tags=["PDF"])
app.include_router(yt_router, prefix="/youtube", tags=["YouTube"])
app.include_router(auth_router, prefix="/auth", tags=["Auth"])
app.include_router(summary.router)


# Simple root endpoint (health check / welcome message).
# Useful for verifying the service is up without authenticating.
@app.get("/")
def root():
    """Return a basic status message to confirm the API is running."""
    return {"message": "Smart Content Finder API is running!"}
